language: csharp
mono: none
dotnet: 3.1
solution: DevOpsDemo.sln
script:
- cd DevOpsDemo
- dotnet restore
- dotnet build
- dotnet test DevOpsDemo_Tests/DevOpsDemo_Tests.csproj
deploy:
  provider: releases
  on:
    branch: develop
  token: 82c2f66770efdcae92fe722525ed2f0c9441eea9
  